node {
  name: "Variable"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_BOOL
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_BOOL
        tensor_shape {
          dim {
            size: 2
          }
          dim {
            size: 3
          }
          dim {
            size: 4
          }
        }
        bool_val: true
        bool_val: true
        bool_val: true
        bool_val: false
        bool_val: true
        bool_val: false
        bool_val: true
        bool_val: true
        bool_val: true
        bool_val: true
        bool_val: false
        bool_val: true
        bool_val: true
        bool_val: true
        bool_val: false
        bool_val: false
        bool_val: false
        bool_val: false
        bool_val: true
        bool_val: true
        bool_val: true
        bool_val: false
        bool_val: true
        bool_val: false
      }
    }
  }
}
node {
  name: "Variable/read"
  op: "Identity"
  input: "Variable"
  attr {
    key: "T"
    value {
      type: DT_BOOL
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@Variable"
      }
    }
  }
}
node {
  name: "All/reduction_indices"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
        }
        tensor_content: "\000\000\000\000\001\000\000\000"
      }
    }
  }
}
node {
  name: "All"
  op: "All"
  input: "Variable/read"
  input: "All/reduction_indices"
  attr {
    key: "Tidx"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "keep_dims"
    value {
      b: true
    }
  }
}
library {
}
