node {
  name: "input_0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_DOUBLE
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 3
        }
        dim {
          size: 4
        }
      }
    }
  }
}
node {
  name: "in0"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_DOUBLE
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_DOUBLE
        tensor_shape {
          dim {
            size: 3
          }
          dim {
            size: 1
          }
          dim {
            size: 4
          }
        }
        tensor_content: "D\322S\355\023d\343\277vG\231\370\262\334\321?-\367\243P\207f\302\277\204Ty^y\246\355?\242\221\223o\372n\317? \373\036.lk\365?\213\205W\211\347\315\362? \203\037H_q\363\277%\026\3125D\337\343?\016\234\361F \n\337\277vo\271\344\302\304\352?\311A\n\227\262\356\344\277"
      }
    }
  }
}
node {
  name: "in0/read"
  op: "Identity"
  input: "in0"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@in0"
      }
    }
  }
}
node {
  name: "ExpandDims/dim"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: -2
      }
    }
  }
}
node {
  name: "ExpandDims"
  op: "ExpandDims"
  input: "input_0"
  input: "ExpandDims/dim"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
  attr {
    key: "Tdim"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "output"
  op: "Add"
  input: "ExpandDims"
  input: "in0/read"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
library {
}
