node {
  name: "Variable"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_DOUBLE
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_DOUBLE
        tensor_shape {
          dim {
            size: 5
          }
          dim {
            size: 5
          }
        }
        tensor_content: "\000\000\000\000\000\000\360?\000\000\000\000\000\000\000@\000\000\000\000\000\000\010@\000\000\000\000\000\000\020@\000\000\000\000\000\000\024@\000\000\000\000\000\000\030@\000\000\000\000\000\000\034@\000\000\000\000\000\000 @\000\000\000\000\000\000\"@\000\000\000\000\000\000$@\000\000\000\000\000\000&@\000\000\000\000\000\000(@\000\000\000\000\000\000*@\000\000\000\000\000\000,@\000\000\000\000\000\000.@\000\000\000\000\000\0000@\000\000\000\000\000\0001@\000\000\000\000\000\0002@\000\000\000\000\000\0003@\000\000\000\000\000\0004@\000\000\000\000\000\0005@\000\000\000\000\000\0006@\000\000\000\000\000\0007@\000\000\000\000\000\0008@\000\000\000\000\000\0009@"
      }
    }
  }
}
node {
  name: "Variable/read"
  op: "Identity"
  input: "Variable"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@Variable"
      }
    }
  }
}
node {
  name: "unstack"
  op: "Unpack"
  input: "Variable/read"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
  attr {
    key: "axis"
    value {
      i: 0
    }
  }
  attr {
    key: "num"
    value {
      i: 5
    }
  }
}
node {
  name: "output/input"
  op: "Pack"
  input: "unstack"
  input: "unstack:1"
  input: "unstack:2"
  input: "unstack:3"
  input: "unstack:4"
  attr {
    key: "N"
    value {
      i: 5
    }
  }
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
  attr {
    key: "axis"
    value {
      i: 0
    }
  }
}
node {
  name: "output/reduction_indices"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 0
      }
    }
  }
}
node {
  name: "output"
  op: "Sum"
  input: "output/input"
  input: "output/reduction_indices"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
  attr {
    key: "Tidx"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "keep_dims"
    value {
      b: false
    }
  }
}
library {
}
