node {
  name: "in_0"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
        }
        float_val: 7.787856101989746
      }
    }
  }
}
node {
  name: "in_0/read"
  op: "Identity"
  input: "in_0"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@in_0"
      }
    }
  }
}
node {
  name: "in_1"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 3
          }
          dim {
            size: 4
          }
          dim {
            size: 5
          }
        }
        tensor_content: "\264\363\240\276\365\312%?6\374\222<\205\2723\276->\022\277F\336>\277\266\373l\277O4\205=\253\247\350>t\200\025\277\325\230~\276\206\262R>(\273\331\276Ki\013??\377\232\277\215\277\207\276\255G\227\277\263&\334>I{[\275\206\350\222\276U\260\036=X\031\032?\202\266\215?.\006H?N\362\233?\254zC?\275\351\202?\270\217%?h\301\013\277\037i\234?\252\347\200\277\305]\002\300\224\362H=\212R\300\276\213\341\310\276/\000\263?\225\000\374?9\257\241\277\006;\276?\014\322\277?\032Y\333\276\266O\336>\254\333]?\354\351\222?\001\237\263?U9\000?\340\365\316>\364\334^\276X(\007?w\021\301\277\324\214\201>7^\207\275\345\355\220>\335!\001\276q\271%>\347\021!>n1q?\225\'+\277\177\257\360>\216\014\253\277"
      }
    }
  }
}
node {
  name: "in_1/read"
  op: "Identity"
  input: "in_1"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@in_1"
      }
    }
  }
}
node {
  name: "in_2"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 3
          }
          dim {
            size: 4
          }
          dim {
            size: 5
          }
        }
        tensor_content: "\334\244\236>\254\212\231><!r?^3 ?\220:\342=\320\007U>\274?p?\330\352\216>\210\314B>\300\212\363>\310\035\346>H24>\250\265\303>\nN`?\020MG?\026\213E?\224\272{?`\253\267=\366,\'?0\026\350=\312\237a?\350\216\316>\370\034\257>X/K>2\350Q?\\\232\357>\010qP?8\335\346>\234\333A? \034\037=(2\213>2\355\024?\260!\264=\310\333\230>4\351\027?\250\0055?\260\375<>\310\271#?\024k\261>\370\211\246>b\307^?8\017N?\200A\022>\316\327L?x\001\023>\250\300p>\30214?0\252\260>\000u\275>\370\021\337>0\247\025?\"\377T?\214@\025?$\032\023?\220Ft?<T\255> \360\355=\000L\325=\010\254\t>\224\216\352>"
      }
    }
  }
}
node {
  name: "in_2/read"
  op: "Identity"
  input: "in_2"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@in_2"
      }
    }
  }
}
node {
  name: "normalize/divisor"
  op: "Reciprocal"
  input: "in_0/read"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "normalize/mean"
  op: "Mul"
  input: "in_1/read"
  input: "normalize/divisor"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "normalize/Mul"
  op: "Mul"
  input: "in_2/read"
  input: "normalize/divisor"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "normalize/Square"
  op: "Square"
  input: "normalize/mean"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "normalize/variance"
  op: "Sub"
  input: "normalize/Mul"
  input: "normalize/Square"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
library {
}
