node {
  name: "input_0"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_DOUBLE
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 3
        }
        dim {
          size: 3
        }
      }
    }
  }
}
node {
  name: "input_1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_DOUBLE
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 3
        }
        dim {
          size: 3
        }
      }
    }
  }
}
node {
  name: "acos1"
  op: "Acos"
  input: "input_0"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "sin2"
  op: "Sin"
  input: "acos1"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "asin3"
  op: "Asin"
  input: "sin2"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "sinh4"
  op: "Sinh"
  input: "asin3"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "floor5"
  op: "Floor"
  input: "sinh4"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "asinh6"
  op: "Asinh"
  input: "floor5"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "minimum7"
  op: "Minimum"
  input: "asinh6"
  input: "input_1"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "cos8"
  op: "Cos"
  input: "minimum7"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "add9"
  op: "Add"
  input: "cos8"
  input: "input_1"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "acosh10"
  op: "Acosh"
  input: "add9"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "atan11"
  op: "Atan"
  input: "acosh10"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "atan212"
  op: "Atan2"
  input: "atan11"
  input: "input_1"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "add13"
  op: "Add"
  input: "atan212"
  input: "input_1"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "elu14"
  op: "Elu"
  input: "add13"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "cosh15"
  op: "Cosh"
  input: "elu14"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "mode16"
  op: "FloorMod"
  input: "cosh15"
  input: "input_1"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "cross17"
  op: "Cross"
  input: "mode16"
  input: "input_1"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "expm18"
  op: "Expm1"
  input: "cross17"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "asinh19"
  op: "Asinh"
  input: "expm18"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "atanh20"
  op: "Atanh"
  input: "asinh19"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "output"
  op: "FloorMod"
  input: "atanh20"
  input: "input_1"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
library {
}
