node {
  name: "loop_var"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 0
      }
    }
  }
}
node {
  name: "loop_var/read"
  op: "Identity"
  input: "loop_var"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@loop_var"
      }
    }
  }
}
node {
  name: "output/Enter"
  op: "Enter"
  input: "loop_var/read"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "frame_name"
    value {
      s: "output/output/"
    }
  }
  attr {
    key: "is_constant"
    value {
      b: false
    }
  }
  attr {
    key: "parallel_iterations"
    value {
      i: 10
    }
  }
}
node {
  name: "output/Merge"
  op: "Merge"
  input: "output/Enter"
  input: "output/NextIteration"
  attr {
    key: "N"
    value {
      i: 2
    }
  }
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "output/Less/y"
  op: "Const"
  input: "^output/Merge"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 10
      }
    }
  }
}
node {
  name: "output/Less"
  op: "Less"
  input: "output/Merge"
  input: "output/Less/y"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "output/LoopCond"
  op: "LoopCond"
  input: "output/Less"
}
node {
  name: "output/Switch"
  op: "Switch"
  input: "output/Merge"
  input: "output/LoopCond"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@output/Merge"
      }
    }
  }
}
node {
  name: "output/Identity"
  op: "Identity"
  input: "output/Switch:1"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "output/Add/y"
  op: "Const"
  input: "^output/Identity"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 1
      }
    }
  }
}
node {
  name: "output/Add"
  op: "Add"
  input: "output/Identity"
  input: "output/Add/y"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "output/NextIteration"
  op: "NextIteration"
  input: "output/Add"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "output/Exit"
  op: "Exit"
  input: "output/Switch"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
library {
}
