node {
  name: "input_1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_DOUBLE
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: -1
        }
        dim {
          size: 3
        }
      }
    }
  }
}
node {
  name: "Add"
  op: "Add"
  input: "input_1"
  input: "input_1"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "Reciprocal"
  op: "Reciprocal"
  input: "Add"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "SquaredDifference"
  op: "SquaredDifference"
  input: "Add"
  input: "Reciprocal"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "w"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_DOUBLE
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_DOUBLE
        tensor_shape {
          dim {
            size: 4
          }
          dim {
            size: 3
          }
        }
        tensor_content: "r\276\343\231\346\231\370?\306w\266\247\334a\304?#%\261dZ\203\271?^\213\030\244 \261\345?%\036\321\364\230O\362?\267\363\216\255\256\221\360\277\263\314qW\034\003\337?\027\0015(Z\267\345\277\261\266\240-\3474\353?g\276\2376Z\333\301?\331I\346\037\242\340\312?Dw\272=\364\247\362\277"
      }
    }
  }
}
node {
  name: "w/read"
  op: "Identity"
  input: "w"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@w"
      }
    }
  }
}
node {
  name: "ReverseV2/axis"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 1
          }
        }
        int_val: -1
      }
    }
  }
}
node {
  name: "ReverseV2"
  op: "ReverseV2"
  input: "w/read"
  input: "ReverseV2/axis"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
  attr {
    key: "Tidx"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "Add_1"
  op: "Add"
  input: "ReverseV2"
  input: "SquaredDifference"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "output"
  op: "Identity"
  input: "Add_1"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
library {
}
