node {
  name: "in0"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_DOUBLE
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_DOUBLE
        tensor_shape {
          dim {
            size: 3
          }
          dim {
            size: 3
          }
        }
        tensor_content: "\335\360L|\357\253\372?4\030\034\335\266\230\303?RS\002~\244Y\000\300w\266\233\275r\232\341\277\206\230]0\346\002\305?\235\263F\334\245,\354?B\255\023\236\351\315\372?I\363\301\2128\226\373?\324\035\217s\325X\362?"
      }
    }
  }
}
node {
  name: "in0/read"
  op: "Identity"
  input: "in0"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@in0"
      }
    }
  }
}
node {
  name: "Add/x"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_DOUBLE
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_DOUBLE
        tensor_shape {
          dim {
            size: 3
          }
          dim {
            size: 3
          }
        }
        tensor_content: "\000\000\000\000\000\000\020\300\000\000\000\000\000\000\010\300\000\000\000\000\000\000\000\300\000\000\000\000\000\000\360\277\000\000\000\000\000\000\000\000\000\000\000\000\000\000\360?\000\000\000\000\000\000\000@\000\000\000\000\000\000\010@\000\000\000\000\000\000\020@"
      }
    }
  }
}
node {
  name: "Add"
  op: "Add"
  input: "Add/x"
  input: "in0/read"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "Abs"
  op: "Abs"
  input: "Add"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "Rsqrt"
  op: "Rsqrt"
  input: "Abs"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
node {
  name: "output"
  op: "Tanh"
  input: "Rsqrt"
  attr {
    key: "T"
    value {
      type: DT_DOUBLE
    }
  }
}
library {
}
