node {
  name: "in0"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 2
          }
          dim {
            size: 5
          }
        }
        tensor_content: "\247G\331?\334\332\266\277\027\002A?&\"\350\275\374\331\204?\021\221\037\2776\271\316\275\215\355\003\300Z0\237>\334\321\370\276"
      }
    }
  }
}
node {
  name: "in0/read"
  op: "Identity"
  input: "in0"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@in0"
      }
    }
  }
}
node {
  name: "input"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 2
        }
        dim {
          size: 5
        }
      }
    }
  }
}
node {
  name: "add"
  op: "Add"
  input: "input"
  input: "in0/read"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "norm_op/mul"
  op: "Mul"
  input: "add"
  input: "add"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "norm_op/Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
        }
        tensor_content: "\000\000\000\000\001\000\000\000"
      }
    }
  }
}
node {
  name: "norm_op/Sum"
  op: "Sum"
  input: "norm_op/mul"
  input: "norm_op/Const"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "Tidx"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "keep_dims"
    value {
      b: true
    }
  }
}
node {
  name: "norm_op/Sqrt"
  op: "Sqrt"
  input: "norm_op/Sum"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "norm_op/Squeeze"
  op: "Squeeze"
  input: "norm_op/Sqrt"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "squeeze_dims"
    value {
      list {
      }
    }
  }
}
node {
  name: "output"
  op: "Identity"
  input: "norm_op/Squeeze"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
library {
}
