node {
  name: "input_1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 16
        }
        dim {
          size: 16
        }
      }
    }
  }
}
node {
  name: "input_2"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 16
        }
        dim {
          size: 16
        }
      }
    }
  }
}
node {
  name: "in0"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 8
          }
          dim {
            size: 1
          }
          dim {
            size: 8
          }
        }
        tensor_content: "V\336\210\277\262FV\277\346\312R\277\340\025/\277\3245\241\277Qe\360\276\026\265|?\262\347\230\276\204#h?o\356\264\277\"\272\231??\030\247>\221\226\\?bMY\277\374\357\340\276\277_\005?\007s\246?\010\203\024\300`\272\336\276\213\205\314\277\347W\376\275\221\033\356>\027\224x>w\335+?\367@\327>\265\213\034\275\255\325\357\276\250U\255?\266=\022>\367\034\251?\006\207\023\277\237\262\003@z\246;\2771L\211\277Dd\365\277\321Z\215\277\222d\201\277\\\t\236\276\376b\326?\362\2014\276E.\220?\341\324{>\021(\337\277\271@M?J\025\255>7\305\366\276\314f\226>\220\311\027\2770\260\034\277T\346\013\300\021b\254> B\227\277\211W\207\276\205\037 ?-9r<]\363\n\276\245\0302\277*\352\036?\014\004\r?{\221&?\315\305\376\277}\212*?t\220\200\276\277\242\200>"
      }
    }
  }
}
node {
  name: "in0/read"
  op: "Identity"
  input: "in0"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@in0"
      }
    }
  }
}
node {
  name: "concat/axis"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: -2
      }
    }
  }
}
node {
  name: "concat"
  op: "ConcatV2"
  input: "input_1"
  input: "input_2"
  input: "concat/axis"
  attr {
    key: "N"
    value {
      i: 2
    }
  }
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "Tidx"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "Reshape/shape"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 3
          }
        }
        tensor_content: "\010\000\000\000\010\000\000\000\010\000\000\000"
      }
    }
  }
}
node {
  name: "Reshape"
  op: "Reshape"
  input: "concat"
  input: "Reshape/shape"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "Tshape"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "Pow"
  op: "Pow"
  input: "Reshape"
  input: "Reshape"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "Tan"
  op: "Tan"
  input: "Pow"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "Neg"
  op: "Neg"
  input: "Tan"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "Mul"
  op: "Mul"
  input: "Neg"
  input: "Pow"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "output"
  op: "Sub"
  input: "Mul"
  input: "in0/read"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
library {
}
