node {
  name: "input_1"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 16
        }
        dim {
          size: 16
        }
      }
    }
  }
}
node {
  name: "input_2"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 16
        }
        dim {
          size: 16
        }
      }
    }
  }
}
node {
  name: "in0"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 8
          }
          dim {
            size: 1
          }
          dim {
            size: 8
          }
        }
        tensor_content: "\323\326\010?\0025\265\277\213\275\002?\326x\'\274/\263\323?\230\203\246\277\347\215\276?#;\357?\273l\027>\374\350\331?KYQ\276\325Ew\277\371\377y>\316\006N\276[\034\013\277\026+\022>\206wF\276Y+\250\275\223\005\020\277\360\036\324\277<\370\300?\374\034\332?\244&\356>\237\315\377\277\250\214I>\266\372\242?\275\345n\276[\362\263?\251]\036>\214\214_\276\257\222\341=~\027!?8\310\016?\304\275\236\277\036\030u\275\n\376.?\377\254%\276M\303\201>\344s*@r0f?\022\305\037?\031\037\270>\3178\202?n\207\273\274j\230\315?B\304\247\277lC\267?\353I\200>T-\030\277\327\251q>\0172\221\2775\362\010\3008\036\202?\300\372\207\277\305\227\005\276J\300\025?U\210\232?\332\240\024@\251;\026\300\002\006n?\373\021\245>H\375\234\276\301\027 ?^\317\003\275"
      }
    }
  }
}
node {
  name: "in0/read"
  op: "Identity"
  input: "in0"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@in0"
      }
    }
  }
}
node {
  name: "concat/axis"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: -2
      }
    }
  }
}
node {
  name: "concat"
  op: "ConcatV2"
  input: "input_1"
  input: "input_2"
  input: "concat/axis"
  attr {
    key: "N"
    value {
      i: 2
    }
  }
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "Tidx"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "Reshape/shape"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 3
          }
        }
        tensor_content: "\010\000\000\000\010\000\000\000\010\000\000\000"
      }
    }
  }
}
node {
  name: "Reshape"
  op: "Reshape"
  input: "concat"
  input: "Reshape/shape"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "Tshape"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "Pow"
  op: "Pow"
  input: "Reshape"
  input: "Reshape"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "Tan"
  op: "Tan"
  input: "Pow"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "Neg"
  op: "Neg"
  input: "Tan"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "Mul"
  op: "Mul"
  input: "Neg"
  input: "Pow"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "output"
  op: "Sub"
  input: "Mul"
  input: "in0/read"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
library {
}
