node {
  name: "input"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: -1
        }
        dim {
          size: 5
        }
      }
    }
  }
}
node {
  name: "l0W"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 5
          }
          dim {
            size: 10
          }
        }
        tensor_content: "/L\251?\271*b\276\023\311\267>\2151q>\351\t\261=\025\034\372=l\347\263?\005<\275\277\324h\213\276]\n\223>Y\201\355\276\357\272\351\276\372\377\337\276fl\010?}\244Q?d(\265?\361\265\020?a\243\205\272i\000\340?l\307\254?\300n\327\276\035\327<?V)G\277%\022\005@\"?\227?\217\342\\?suO?g\376v?\244l\326\277L\306\237>\307\325\237\276~\215z\276B)h?\262\200\207\276\304\253j?\007\302\265>\204\277\312?\273.\002\277\210\303Y?\2578)>\303AF?\241d\017\277\322\253\275>f\027\215;\343\330\224\276\301\273M?\034\027E>\020H\373\276TI^\276s\251\262?"
      }
    }
  }
}
node {
  name: "l0W/read"
  op: "Identity"
  input: "l0W"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@l0W"
      }
    }
  }
}
node {
  name: "l1W"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 10
          }
          dim {
            size: 3
          }
        }
        tensor_content: "<\351L\277.\212\002\277R\271\273?\247\313`?t\261_\277g\002\231?M\014\332?\'\356\257?KM\277>\017\347\371\277\227\001\247\277\234t\220?\301\312\243\277\222\213\222\276\034\233\020\300\036\216V\276x\010\245\275\370;$\277R.(\277/NH\277u\257\301\277\244\317\316?\221\210\236\277\007\225)?\034\013E?\030+\037\277\321jV\277\241\220\217>O\001\316\276\217j\026?"
      }
    }
  }
}
node {
  name: "l1W/read"
  op: "Identity"
  input: "l1W"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@l1W"
      }
    }
  }
}
node {
  name: "l0B"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 10
          }
        }
        tensor_content: "\177\007\376\276j\3067?{\000\024?\305-\212?OV\232?\321\375\237>\362\203\006>q*\205?\017%\235>\300\237\351\276"
      }
    }
  }
}
node {
  name: "l0B/read"
  op: "Identity"
  input: "l0B"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@l0B"
      }
    }
  }
}
node {
  name: "l1B"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 3
          }
        }
        tensor_content: "\334\022\346>\277\031\375\276\266\021\223\277"
      }
    }
  }
}
node {
  name: "l1B/read"
  op: "Identity"
  input: "l1B"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@l1B"
      }
    }
  }
}
node {
  name: "MatMul"
  op: "MatMul"
  input: "input"
  input: "l0W/read"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "transpose_a"
    value {
      b: false
    }
  }
  attr {
    key: "transpose_b"
    value {
      b: false
    }
  }
}
node {
  name: "l0Preout"
  op: "BiasAdd"
  input: "MatMul"
  input: "l0B/read"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "data_format"
    value {
      s: "NHWC"
    }
  }
}
node {
  name: "l0Out"
  op: "Abs"
  input: "l0Preout"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "MatMul_1"
  op: "MatMul"
  input: "l0Out"
  input: "l1W/read"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "transpose_a"
    value {
      b: false
    }
  }
  attr {
    key: "transpose_b"
    value {
      b: false
    }
  }
}
node {
  name: "l1PreOut"
  op: "BiasAdd"
  input: "MatMul_1"
  input: "l1B/read"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "data_format"
    value {
      s: "NHWC"
    }
  }
}
node {
  name: "output"
  op: "Softmax"
  input: "l1PreOut"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
library {
}
