node {
  name: "Variable"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_BOOL
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_BOOL
        tensor_shape {
          dim {
            size: 5
          }
        }
        bool_val: true
        bool_val: true
        bool_val: true
        bool_val: false
        bool_val: true
      }
    }
  }
}
node {
  name: "Variable/read"
  op: "Identity"
  input: "Variable"
  attr {
    key: "T"
    value {
      type: DT_BOOL
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@Variable"
      }
    }
  }
}
node {
  name: "in_1"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 5
          }
          dim {
            size: 4
          }
        }
        tensor_content: "\324\325_? \310n?0\301D?\032 f?\250a<?\320\335\013>\200\224r>\206pV?\324\300\260>\264\376\347>@\336\354=d/\356>\332\227`?\300\201\037=\300\256\305=\014g\243>\350=\322>\244\352\265>t\255\254>\274h\316>"
      }
    }
  }
}
node {
  name: "in_1/read"
  op: "Identity"
  input: "in_1"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@in_1"
      }
    }
  }
}
node {
  name: "in_2"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 5
          }
          dim {
            size: 4
          }
        }
        tensor_content: "\034\345I?\336\311F?\210\237L?\246\330`?\260o3?\364CL?\324]\234>\\\2307?\200`Z>\326\363\002?\360\027\005>r\305\010?\000zk;\030\242L>`\235\310=\354H\304>\010\376T>V\212.?H\277d>x\006\273>"
      }
    }
  }
}
node {
  name: "in_2/read"
  op: "Identity"
  input: "in_2"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@in_2"
      }
    }
  }
}
node {
  name: "Select"
  op: "Select"
  input: "Variable/read"
  input: "in_1/read"
  input: "in_2/read"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
library {
}
