node {
  name: "in_0"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 3
          }
          dim {
            size: 4
          }
        }
        tensor_content: "~^G?L\033M?\236p9?\220ol>\356%:?X\2708><q\001?b|d?\224\316\013?\314al?P@\257=,5K?"
      }
    }
  }
}
node {
  name: "in_0/read"
  op: "Identity"
  input: "in_0"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@in_0"
      }
    }
  }
}
node {
  name: "in_1"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 3
          }
          dim {
            size: 4
          }
        }
        tensor_content: "\264\363\240\276\365\312%?6\374\222<\205\2723\276->\022\277F\336>\277\266\373l\277O4\205=\253\247\350>t\200\025\277\325\230~\276\206\262R>"
      }
    }
  }
}
node {
  name: "in_1/read"
  op: "Identity"
  input: "in_1"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@in_1"
      }
    }
  }
}
node {
  name: "in_2"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 3
          }
          dim {
            size: 1
          }
        }
        tensor_content: "\000\000\000\000\254\212\231><!r?"
      }
    }
  }
}
node {
  name: "in_2/read"
  op: "Identity"
  input: "in_2"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@in_2"
      }
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/xentropy/zeros_like"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 3
          }
          dim {
            size: 4
          }
        }
        float_val: 0.0
      }
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/xentropy/GreaterEqual"
  op: "GreaterEqual"
  input: "in_1/read"
  input: "sigmoid_cross_entropy_loss/xentropy/zeros_like"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/xentropy/Select"
  op: "Select"
  input: "sigmoid_cross_entropy_loss/xentropy/GreaterEqual"
  input: "in_1/read"
  input: "sigmoid_cross_entropy_loss/xentropy/zeros_like"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/xentropy/Neg"
  op: "Neg"
  input: "in_1/read"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/xentropy/Select_1"
  op: "Select"
  input: "sigmoid_cross_entropy_loss/xentropy/GreaterEqual"
  input: "sigmoid_cross_entropy_loss/xentropy/Neg"
  input: "in_1/read"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/xentropy/mul"
  op: "Mul"
  input: "in_1/read"
  input: "in_0/read"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/xentropy/sub"
  op: "Sub"
  input: "sigmoid_cross_entropy_loss/xentropy/Select"
  input: "sigmoid_cross_entropy_loss/xentropy/mul"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/xentropy/Exp"
  op: "Exp"
  input: "sigmoid_cross_entropy_loss/xentropy/Select_1"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/xentropy/Log1p"
  op: "Log1p"
  input: "sigmoid_cross_entropy_loss/xentropy/Exp"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/xentropy"
  op: "Add"
  input: "sigmoid_cross_entropy_loss/xentropy/sub"
  input: "sigmoid_cross_entropy_loss/xentropy/Log1p"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/assert_broadcastable/static_dims_check_success"
  op: "NoOp"
}
node {
  name: "sigmoid_cross_entropy_loss/Mul"
  op: "Mul"
  input: "sigmoid_cross_entropy_loss/xentropy"
  input: "in_2/read"
  input: "^sigmoid_cross_entropy_loss/assert_broadcastable/static_dims_check_success"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/Const"
  op: "Const"
  input: "^sigmoid_cross_entropy_loss/assert_broadcastable/static_dims_check_success"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
        }
        tensor_content: "\000\000\000\000\001\000\000\000"
      }
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/Sum"
  op: "Sum"
  input: "sigmoid_cross_entropy_loss/Mul"
  input: "sigmoid_cross_entropy_loss/Const"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "Tidx"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "keep_dims"
    value {
      b: false
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/num_present/Equal/y"
  op: "Const"
  input: "^sigmoid_cross_entropy_loss/assert_broadcastable/static_dims_check_success"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
        }
        float_val: 0.0
      }
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/num_present/Equal"
  op: "Equal"
  input: "in_2/read"
  input: "sigmoid_cross_entropy_loss/num_present/Equal/y"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/num_present/zeros_like"
  op: "Const"
  input: "^sigmoid_cross_entropy_loss/assert_broadcastable/static_dims_check_success"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 3
          }
          dim {
            size: 1
          }
        }
        float_val: 0.0
      }
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/num_present/ones_like/Shape"
  op: "Const"
  input: "^sigmoid_cross_entropy_loss/assert_broadcastable/static_dims_check_success"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
        }
        tensor_content: "\003\000\000\000\001\000\000\000"
      }
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/num_present/ones_like/Const"
  op: "Const"
  input: "^sigmoid_cross_entropy_loss/assert_broadcastable/static_dims_check_success"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
        }
        float_val: 1.0
      }
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/num_present/ones_like"
  op: "Fill"
  input: "sigmoid_cross_entropy_loss/num_present/ones_like/Shape"
  input: "sigmoid_cross_entropy_loss/num_present/ones_like/Const"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "index_type"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/num_present/Select"
  op: "Select"
  input: "sigmoid_cross_entropy_loss/num_present/Equal"
  input: "sigmoid_cross_entropy_loss/num_present/zeros_like"
  input: "sigmoid_cross_entropy_loss/num_present/ones_like"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/num_present/broadcast_weights/assert_broadcastable/static_dims_check_success"
  op: "NoOp"
  input: "^sigmoid_cross_entropy_loss/assert_broadcastable/static_dims_check_success"
}
node {
  name: "sigmoid_cross_entropy_loss/num_present/broadcast_weights/ones_like/Shape"
  op: "Const"
  input: "^sigmoid_cross_entropy_loss/assert_broadcastable/static_dims_check_success"
  input: "^sigmoid_cross_entropy_loss/num_present/broadcast_weights/assert_broadcastable/static_dims_check_success"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
        }
        tensor_content: "\003\000\000\000\004\000\000\000"
      }
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/num_present/broadcast_weights/ones_like/Const"
  op: "Const"
  input: "^sigmoid_cross_entropy_loss/assert_broadcastable/static_dims_check_success"
  input: "^sigmoid_cross_entropy_loss/num_present/broadcast_weights/assert_broadcastable/static_dims_check_success"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
        }
        float_val: 1.0
      }
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/num_present/broadcast_weights/ones_like"
  op: "Fill"
  input: "sigmoid_cross_entropy_loss/num_present/broadcast_weights/ones_like/Shape"
  input: "sigmoid_cross_entropy_loss/num_present/broadcast_weights/ones_like/Const"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "index_type"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/num_present/broadcast_weights"
  op: "Mul"
  input: "sigmoid_cross_entropy_loss/num_present/Select"
  input: "sigmoid_cross_entropy_loss/num_present/broadcast_weights/ones_like"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/num_present/Const"
  op: "Const"
  input: "^sigmoid_cross_entropy_loss/assert_broadcastable/static_dims_check_success"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
        }
        tensor_content: "\000\000\000\000\001\000\000\000"
      }
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/num_present"
  op: "Sum"
  input: "sigmoid_cross_entropy_loss/num_present/broadcast_weights"
  input: "sigmoid_cross_entropy_loss/num_present/Const"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "Tidx"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "keep_dims"
    value {
      b: false
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/Const_1"
  op: "Const"
  input: "^sigmoid_cross_entropy_loss/assert_broadcastable/static_dims_check_success"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
          }
        }
      }
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/Sum_1"
  op: "Sum"
  input: "sigmoid_cross_entropy_loss/Sum"
  input: "sigmoid_cross_entropy_loss/Const_1"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "Tidx"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "keep_dims"
    value {
      b: false
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/Greater/y"
  op: "Const"
  input: "^sigmoid_cross_entropy_loss/assert_broadcastable/static_dims_check_success"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
        }
        float_val: 0.0
      }
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/Greater"
  op: "Greater"
  input: "sigmoid_cross_entropy_loss/num_present"
  input: "sigmoid_cross_entropy_loss/Greater/y"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/Equal/y"
  op: "Const"
  input: "^sigmoid_cross_entropy_loss/assert_broadcastable/static_dims_check_success"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
        }
        float_val: 0.0
      }
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/Equal"
  op: "Equal"
  input: "sigmoid_cross_entropy_loss/num_present"
  input: "sigmoid_cross_entropy_loss/Equal/y"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/ones_like/Shape"
  op: "Const"
  input: "^sigmoid_cross_entropy_loss/assert_broadcastable/static_dims_check_success"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
          }
        }
      }
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/ones_like/Const"
  op: "Const"
  input: "^sigmoid_cross_entropy_loss/assert_broadcastable/static_dims_check_success"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
        }
        float_val: 1.0
      }
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/ones_like"
  op: "Fill"
  input: "sigmoid_cross_entropy_loss/ones_like/Shape"
  input: "sigmoid_cross_entropy_loss/ones_like/Const"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "index_type"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/Select"
  op: "Select"
  input: "sigmoid_cross_entropy_loss/Equal"
  input: "sigmoid_cross_entropy_loss/ones_like"
  input: "sigmoid_cross_entropy_loss/num_present"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/div"
  op: "RealDiv"
  input: "sigmoid_cross_entropy_loss/Sum_1"
  input: "sigmoid_cross_entropy_loss/Select"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/zeros_like"
  op: "Const"
  input: "^sigmoid_cross_entropy_loss/assert_broadcastable/static_dims_check_success"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
        }
        float_val: 0.0
      }
    }
  }
}
node {
  name: "sigmoid_cross_entropy_loss/value"
  op: "Select"
  input: "sigmoid_cross_entropy_loss/Greater"
  input: "sigmoid_cross_entropy_loss/div"
  input: "sigmoid_cross_entropy_loss/zeros_like"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
library {
}
